version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:15"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:45"
      timezone: Etc/UTC
    labels:
      - dependencies
      - javascript
    groups:
      next:
        patterns:
          - "next"
          - "eslint-config-next"
          - "react"
          - "react-dom"
      node-dev-tools:
        patterns:
          - "*"
