---
kind: pipeline
type: kubernetes
name: build-and-push

trigger:
  event:
    - push
  ref:
    include:
      - refs/heads/main
      - refs/tags/v*

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      registry: git.scruzzi.com
      repo: git.scruzzi.com/mattia/scruzzi-website
      auto_tag: true
      username:
        from_secret: gitea_registry_user
      password:
        from_secret: gitea_registry_password
