---
kind: pipeline
type: kubernetes
name: release

trigger:
  event:
    - push
  ref:
    include:
      - refs/heads/main

steps:
  - name: release
    image: alpine
    commands:
      - echo "PLUGIN_TOKEN=$PLUGIN_TOKEN"
      - echo "ENV TOKEN=$GITEA_TOKEN"
      - env | grep -i token || true
