name: Lint & Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js (for HTML Hint)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Lint HTML Code
        run: htmlhint index.html

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Gitea Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login git.scruzzi.com -u ${{ gitea.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          # Image Tags definieren
          REPO_LOWER=$(echo "${{ gitea.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG_LATEST="git.scruzzi.com/${REPO_LOWER}:latest"
          IMAGE_TAG_SHA="git.scruzzi.com/${REPO_LOWER}:${{ gitea.sha }}"
          
          echo "Bauen: ${IMAGE_TAG_LATEST}"
          docker build -t ${IMAGE_TAG_LATEST} -t ${IMAGE_TAG_SHA} .
          
          echo "Pushen..."
          docker push ${IMAGE_TAG_LATEST}
          docker push ${IMAGE_TAG_SHA}
