name: Lint & Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js (for HTML Hint)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Lint HTML Code
        run: htmlhint index.html

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Gitea Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login 192.168.1.41:3000 --username "${{ github.actor }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          # Pfade in Kleinschreibung konvertieren
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "scruzzi--website" | tr '[:upper:]' '[:lower:]')
          
          # Tagging-Schema exakt wie in npm-stats: REGISTRY/OWNER/REPO/IMAGE:TAG
          IMAGE_TAG_LATEST="192.168.1.41:3000/${REPO_OWNER}/${REPO_NAME}/nice-bauch:latest"
          IMAGE_TAG_SHA="192.168.1.41:3000/${REPO_OWNER}/${REPO_NAME}/nice-bauch:${{ github.sha }}"
          
          echo "Bauen: ${IMAGE_TAG_LATEST}"
          docker build -t ${IMAGE_TAG_LATEST} -t ${IMAGE_TAG_SHA} .
          
          echo "Pushen..."
          docker push ${IMAGE_TAG_LATEST}
          docker push ${IMAGE_TAG_SHA}
